### ISSUE TITLE
ISO 8601 Date Recognition Support

### ISSUE THREAD

**Issue by itopaloglu83** [kindly/csvs_convert#10]
I'm not very familiar with Rust so I couldn't create a pull request for this. Would it be possible to add ISO 8601 date-time support to the type recognition? Thank you.

`2024-06-16T04:24:41.994Z`

As far as I can surmise, adding one more format string into this function would suffice but I cannot be sure with Rust.
https://github.com/kindly/csvs_convert/blob/8525540598372f637d67410985fdb29cd4baf3dd/src/describer.rs#L92-L104

**Comment by kindly** [comment]
@itopaloglu83   Date format that are like `2024-06-16T04:24:41.994Z` are supported under rfc3339 which is one of the allowed format in the type recognition.
https://github.com/kindly/csvs_convert/blob/8525540598372f637d67410985fdb29cd4baf3dd/src/describer.rs#L22

The complication here (as far as I understand) there are some  ISO 8601  that do not fall into rfc3339 and vice versa.  I went with rfc3339 as it is what the date library already has a parser for and is the most common.   I think writing my own  ISO 8601 parser is out of scope for this.  However, it is rare for people to publish data that is  ISO 8601 and not rfc3339.
So are you sure your data and does not contain any formatting errors? If a single one is mis-formateed, the date dection will fall back to being text.

**Comment by itopaloglu83** [comment]
Here's the simplest case I was able to repeat the issue. 

``` JSON
[ {"Date": "2024-06-16T04:24:41.994Z", "Capacity": 0, "Load": 0, "Idle": 0} ]
```

Automatically created `fields.csv` says that the column format should be of date. However, the Postgres schema is still showing text. Once the trailing `Z` character is removed, both files match.

``` CSV
table_name,field_name,field_type,field_title,count
Sample,_link,text,_link,1
Sample,Date,date,Date,1
Sample,Capacity,number,Capacity,1
Sample,Load,number,Load,1
Sample,Idle,number,Idle,1
```

``` SQL
CREATE TABLE "sample" (
    "_link" TEXT,
    "date" TEXT,
    "capacity" NUMERIC,
    "load" NUMERIC,
    "idle" NUMERIC
);
```

**Comment by kindly** [comment]
@itopaloglu83 oh it only is effecting Postgres.

It is this function that is wrong then and should have another condition which has timestamp_tz in it:

https://github.com/kindly/csvs_convert/blob/main/src/converters.rs#L618-L642

I will need to do some checks to see if all the datetimes are actually accepted by postgres as currently we do not modify the input date to put it in a format that postgres likes.

**Comment by itopaloglu83** [comment]
Looks like the same issue exists with the dataframe export as well. I’m going to look into why it might be happening. My guess is that `pandas.read_csv(csv_path)` no longer infers the data types or expects some additional arguments.

**Comment by itopaloglu83** [comment]
I must be doing something wrong because even the following JSON results in a `postgresql_schema.sql` file with the TEXT column type.

``` JSON
[ {"Date": "2024-06-16 04:24:41"} ]
```

**Comment by kindly** [comment]
@itopaloglu83   The dates `2024-06-16T04:24:41.994Z`  and `2024-06-16 04:24:41` should now be supported in the latest release of this and flatterer, at least in postgres.

**Comment by kindly** [comment]
I am closing this. I think it should be only dataframes that have these issues, but that is definitely part of python bit of flatterer, so not relevant here.

**Comment by itopaloglu83** [comment]
Thank you, again! This is awesome.
