### ISSUE TITLE
bump dependencies to latest version

### ISSUE THREAD

**Issue by jqnatividad** [kindly/csvs_convert#11]
Several dependencies are a bit behind - rusqlite, duckdb, counter, snafu, typed-builder and zip.

The zip crate has new maintainers as it was unmaintained for a bit.
You may want to upgrade it to the latest 2.x version which has several bug fixes and performance improvements.

**Comment by kindly** [comment]
Thanks @jqnatividad I have bumped the version of all immediate deps to their latest versions in a new release.
