### ISSUE TITLE
bump dependencies

### ISSUE THREAD

**Issue by jqnatividad** [kindly/csvs_convert#3]
Apart from `arrow` and `parquet` dependencies, several other dependencies are not current.  Could they be upgraded as well, or at least pinned to the desired version?

![Screenshot 2022-12-18 at 10 56 30 AM](https://user-images.githubusercontent.com/1980690/208307558-f84b7344-dc54-4597-b607-fc28403e9916.png)

**Comment by kindly** [comment]
all dependancies have been upgraded in the latest verson
