### ISSUE TITLE
postgres numeric type inferencing issue

### ISSUE THREAD

**Issue by jqnatividad** [kindly/csvs_convert#6]
Hi @kindly,
While testing the `qsv to postgres` command, I found this error when trying to copy the following file to postgres.

https://github.com/jqnatividad/qsv/blob/master/resources/test/boston311-100.csv

`qsv to postgres "postgres://testuser:test123@localhost/testdb" boston311-100.csv`
Conversion error: PostgresError { source: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22003), message: "value \"101004143000\" is out of range for type integer", detail: None, hint: None, position: None, where_: Some("COPY boston311-100, line 2, column case_enquiry_id: \"101004143000\""), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("numutils.c"), line: Some(229), routine: Some("pg_strtoint32") }) } }

I know that this is a qsv error, but I opened the issue here as it seems `csvs_converts`'s type inferencing should take into account the min/max values from the stats it uses to infer the data type of a column to select the proper postgres numeric type.
https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by kindly** [comment]
@jqnatividad 

I have gone for the lazier option of just making all postgresql ints `bigints` for now.  This is inline with the parquet conversion, which also does this. 

Just released version 0.8.3 which does this.

**Comment by jqnatividad** [comment]
Thanks @kindly for the quick turnaround!
