### ISSUE TITLE
Truncate Support

### ISSUE THREAD

**Issue by itopaloglu83** [kindly/csvs_convert#9]
First of all, thank you for the flatterer tool, it's great.

Is it possible to add truncate support just like the drop or something similar to a type definitions? The API I'm pulling data from doesn't have a JSON Schema so I ended up making a couple of changes to the `postgresql_schema.sql` file. I'm looking for ways to update the data in the database (remove old, add new) without recreating the tables.

I was hoping to achieve this through the fields file but the documentation says it's ignored.

**Comment by kindly** [comment]
@itopaloglu83 I am sorry I do not understand what you mean here.  Could you try and add more detail or an example.

**Comment by itopaloglu83** [comment]
Sure thing.

Currently, there are two different ways to push data to a database. One can either a) append the data to an existing table, or b) replace the entire table with the new data (the drop table option). I was wondering if it would be possible to add a third option that truncates all the existing data in the table and then appends the new data into that existing table. 

What's the use case? When using data analysis tools like Metabase, it would be quite handy to just replace the data with the updated one without recreating the tables etc. It ensures that underlying SQL queries do not error out due to schema changes.

**Comment by itopaloglu83** [comment]
Thank you!
